#!/usr/bin/env node
/*
 * Shared Ed25519 signing helpers for the MT-Billing vendor activator.
 *
 * Codes are signatures, not shared-secret HMACs: the private key generated by
 * generate-keys.cjs must stay on the vendor's machine and MUST NEVER be
 * committed to git or bundled into a distributable. Only the matching public
 * key (pasted into server/src/panelId.ts) is safe to ship to customers.
 */
'use strict';

const crypto = require('crypto');
const fs = require('fs');

const BASE32_ALPHABET = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ234567';

function base32Encode(buf) {
  let bits = 0;
  let value = 0;
  let output = '';
  for (const byte of buf) {
    value = (value << 8) | byte;
    bits += 8;
    while (bits >= 5) {
      output += BASE32_ALPHABET[(value >>> (bits - 5)) & 31];
      bits -= 5;
    }
  }
  if (bits > 0) output += BASE32_ALPHABET[(value << (5 - bits)) & 31];
  return output;
}

function chunk(s, size) {
  const n = size || 5;
  const parts = [];
  for (let i = 0; i < s.length; i += n) parts.push(s.slice(i, i + n));
  return parts.join('-');
}

function normalizeCode(k) {
  return String(k || '')
    .toUpperCase()
    .replace(/[^A-Z0-9]/g, '');
}

const DURATIONS = [
  { id: '30d', label: '30 days' },
  { id: '90d', label: '90 days' },
  { id: '180d', label: '6 months' },
  { id: '1y', label: '1 year' },
  { id: '2y', label: '2 years' },
  { id: 'life', label: 'Lifetime' },
];

/** Base directory to look for a private key next to — works both as `node activator.cjs`
 *  and as a `pkg`-built exe (process.execPath is the real exe path, not the virtual snapshot fs). */
function baseDir() {
  return process.pkg ? require('path').dirname(process.execPath) : __dirname;
}

function defaultKeyPath() {
  return require('path').join(baseDir(), 'keys', 'vendor-private-key.pem');
}

/** Load the vendor's Ed25519 private key from (in order): explicit path/PEM, MT_BILLING_VENDOR_KEY env, default keys/ dir. */
function loadPrivateKey(explicit) {
  let source = explicit || process.env.MT_BILLING_VENDOR_KEY || defaultKeyPath();
  let pem = source;
  if (!String(source).includes('BEGIN PRIVATE KEY')) {
    if (!fs.existsSync(source)) {
      throw new Error(
        `Vendor private key not found at ${source}\n` +
          `Run "node generate-keys.cjs" once to create it, or pass --key <path-to-pem>.`
      );
    }
    pem = fs.readFileSync(source, 'utf8');
  }
  return crypto.createPrivateKey(pem);
}

function signLicenseKey(privateKey, hwid, durationId) {
  const id = String(durationId || 'life').toLowerCase();
  const known = DURATIONS.find((d) => d.id === id);
  const dur = known ? known.id : 'life';
  const norm = normalizeCode(hwid);
  const message = `LIC|${norm}|${dur}`;
  const sig = crypto.sign(null, Buffer.from(message, 'utf8'), privateKey);
  return chunk(base32Encode(sig)) + '-' + dur.toUpperCase();
}

function signResetCode(privateKey, hwid) {
  const norm = normalizeCode(hwid);
  const message = `RST|${norm}`;
  const sig = crypto.sign(null, Buffer.from(message, 'utf8'), privateKey);
  return 'RST-' + chunk(base32Encode(sig));
}

module.exports = {
  DURATIONS,
  normalizeCode,
  base32Encode,
  chunk,
  defaultKeyPath,
  loadPrivateKey,
  signLicenseKey,
  signResetCode,
};
