#!/usr/bin/env bash
# Copyright (c) 2026 MT-Billing / ts0gs
# License: MIT
#
# Ensure a public hostname (typically the Cloudflare Tunnel hostname) serves
# the FULL panel — including /login and /api/login — instead of a pay-only
# nginx vhost that returns 404 for everything except /pay/*.
#
# Usage (root):
#   sudo bash /opt/mt-billing/install/mt-billing-nginx-staff-host.sh pay.yourdomain.com
#
# Safe to re-run. Keeps LAN default_server as full panel. Leaves a separate
# pay-only vhost alone only when its server_name does not match HOSTNAME.

set -euo pipefail

INSTALL_DIR="${var_install_dir:-${INSTALL_DIR:-/opt/mt-billing}}"
API_PORT="${var_api_port:-${API_PORT:-4000}}"
PANEL_PORT="${var_panel_port:-${PANEL_PORT:-80}}"
HOSTNAME="${1:-}"
SITE_AVAIL="/etc/nginx/sites-available/mt-billing"
SITE_ENABLED="/etc/nginx/sites-enabled/mt-billing"

log_info() { printf '\033[1;34m[INFO]\033[0m %s\n' "$*"; }
log_ok() { printf '\033[1;32m[OK]\033[0m %s\n' "$*"; }
log_err() { printf '\033[1;31m[ERROR]\033[0m %s\n' "$*" >&2; }
log_warn() { printf '\033[1;33m[WARN]\033[0m %s\n' "$*"; }

if [[ "$(id -u)" -ne 0 ]]; then
  log_err "Run as root"
  exit 1
fi

HOSTNAME="$(printf '%s' "$HOSTNAME" | sed -E 's#^https?://##; s#/.*##; s/[[:space:]]//g' | tr '[:upper:]' '[:lower:]')"
if [[ -z "$HOSTNAME" || "$HOSTNAME" == "pay.yourisp.com" ]]; then
  log_err "Pass a real public hostname (e.g. pay.yourdomain.com)"
  exit 1
fi

detect_lan_ip() {
  local ip=""
  ip="$(hostname -I 2>/dev/null | awk '{print $1}')"
  if [[ -z "$ip" ]] && command -v ip >/dev/null 2>&1; then
    ip="$(ip -4 route get 1.1.1.1 2>/dev/null | awk '{for(i=1;i<=NF;i++) if($i=="src"){print $(i+1); exit}}')"
  fi
  printf '%s' "$ip"
}

LAN_IP="$(detect_lan_ip)"

full_locations() {
  cat <<EOF
    location /api/ {
        proxy_pass http://127.0.0.1:${API_PORT}/api/;
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_read_timeout 86400;
        # Same machine via LAN IP or Cloudflare hostname must see live DB data
        add_header Cache-Control "private, no-store, no-cache, must-revalidate" always;
        add_header Pragma "no-cache" always;
        expires -1;
    }
    location = /index.html {
        add_header Cache-Control "no-store, no-cache, must-revalidate" always;
        try_files /index.html =404;
    }
    location = /pay {
        try_files /index.html =404;
    }
    location ^~ /pay/ {
        try_files \$uri /index.html;
    }
    location / {
        try_files \$uri \$uri/ /index.html;
    }
EOF
}

mkdir -p "$(dirname "$SITE_AVAIL")"
FULL="$(full_locations)"

# Always write: CF/public hostname = full panel; LAN/default = full panel.
# (Pay-only on the tunnel hostname is what blocks staff login.)
cat >"$SITE_AVAIL" <<EOF
# MT-Billing — Cloudflare / public hostname (FULL panel: login + API + pay)
# Generated by mt-billing-nginx-staff-host.sh
server {
    listen ${PANEL_PORT};
    listen [::]:${PANEL_PORT};
    server_name ${HOSTNAME};
    client_max_body_size 300m;

    root ${INSTALL_DIR}/client/dist;
    index index.html;

${FULL}
}

# MT-Billing — LAN / default (full panel)
server {
    listen ${PANEL_PORT} default_server;
    listen [::]:${PANEL_PORT} default_server;
    server_name ${LAN_IP:-_} localhost _;
    client_max_body_size 300m;

    root ${INSTALL_DIR}/client/dist;
    index index.html;

${FULL}
}
EOF

ln -sfn "$SITE_AVAIL" "$SITE_ENABLED" 2>/dev/null || true
# Remove default sites that steal the Host
rm -f /etc/nginx/sites-enabled/default 2>/dev/null || true

if nginx -t 2>/dev/null; then
  systemctl reload nginx 2>/dev/null || service nginx reload 2>/dev/null || nginx -s reload 2>/dev/null || true
  log_ok "nginx: ${HOSTNAME} serves full panel (login + /api/)"
else
  log_warn "nginx -t failed — config written to ${SITE_AVAIL}; fix and reload manually"
  exit 1
fi

echo "  Staff login : https://${HOSTNAME}/login"
echo "  LAN login   : http://${LAN_IP:-<lan-ip>}/login"
echo "  Reminder    : disable Cloudflare Access + Bot Fight on this hostname or POST /api/login is blocked at the edge."
